services:
  db:
    image: kartoza/postgis
    container_name: ping-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ping_db
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    networks:
      - ping_network

  test_db:
    image: kartoza/postgis
    container_name: ping-db-test
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ping_db
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5433:5432"
    volumes:
      - db_data_test:/var/lib/postgresql
      - ./db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    networks:
      - ping_network

  redis:
    image: redis:7.0
    container_name: ping-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ping_network
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  minio:
    image: minio/minio
    container_name: ping-minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address :9001
    networks:
      - ping_network

  backend:
    build: ./backend
    container_name: ping-backend
    restart: always
    environment:
      DB_HOST: ping-db
      DB_HOST_TEST: ping-db-test
      DB_PORT: 5432
      DB_NAME: ping_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ping-redis
      REDIS_PORT: 6379
      S3_ENDPOINT: ping-minio:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ping-bucket
      SECRET_KEY: ${SECRET_KEY}
      EXPIRE_TIME: ${EXPIRE_TIME}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - ping_network
    volumes:
      - ./backend:/app
  
  frontend:
    build: ./frontend
    container_name: ping-frontend
    restart: always
    environment:
      API_URL: http://ping-backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ping_network
    volumes:
      - ./frontend:/app


volumes:
  db_data:
  db_data_test:
  redis_data:
  minio_data:

networks:
  ping_network:
    driver: bridge
